name: GitHub Actions Demo
on:
  push:
    branches:
      - test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites 
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install databricks-cli
        cat > ~/.databrickscfg <<EOF 
        [DEFAULT] 
        host = https://adb-3355368943779169.9.azuredatabricks.net
        token = $(echo "${{ secrets.DATABRICKS_TOKEN }}") 
        EOF
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Import prod notebook
      run: |
        databricks workspace import_dir -o ${{ github.workspace }}/notebooks /Test
    - name: 'Run Python Unit Tests'
      run: |
        python -m pytest ${{ github.workspace }}/uTests/*
